name: Testnet Bug Report
description: Create a report to help us get it right
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of what the bug is.
      placeholder: What currently happens and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps
      description: The steps to reproduce the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I've expected...

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other

  - type: input
      id: other_browser
      attributes:
        label: Other browser
        placeholder: Fill this field if your browser is not in the list above.

  - type: dropdown
    id: wallets
    attributes:
      label: Which wallet you are using?
      multiple: true
      options:
        - PolkadotJS
        - Talisman
        - Nova Wallet
        - SubWallet

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload screenshots/video.
      placeholder: Drag and drop screenshots/video here.

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional context or information you feel may be relevant to the issue.
